### ISSUE TITLE
No Monterey?

### ISSUE THREAD

**Issue by Fred-IV** [alienator88/Sentinel#1]
It wouldn't work on less than macOS 13, so I downloaded v1.0, and that one doesn't either.
Can you compile it to work on 12?

**Comment by alienator88** [comment]
I’ll need to check if any swift functions I’m using in it depend on 13.0. If they don’t, I’ll try to downgrade it and push out a new update.

**Comment by alienator88** [comment]
Pushed out a new version that should work on macOS 12 and up.
