### ISSUE TITLE
`brew update` replaces Sentinel with a different Cask

### ISSUE THREAD

**Issue by bennygoldman** [alienator88/Sentinel#3]
has happened twice now. new to brew. any way to persist which cask gets downloaded? every time i run brew upgrade, a different cask gets downloaded and this app is removed.

https://formulae.brew.sh/cask/sentinel

**Comment by alienator88** [comment]
Ah, I wasn't aware that there was a cask named sentinel in the official brew repo.
I've renamed the cask to `sentinel-app` to avoid the name duplication.

First uninstall the existing cask using: 
`brew uninstall alienator88/homebrew-cask/sentinel`

Now install again using this command and brew upgrade should not have any issues next time:
`brew install alienator88/homebrew-cask/sentinel-app`

**Comment by bennygoldman** [comment]
ty!
