### ISSUE TITLE
The website still give the old homebrew command

### ISSUE THREAD

**Issue by weatheredwatcher** [alienator88/Sentinel#4]
I noticed that you had an issue with naming conflicts in homebrew.  The website still has 

```brew install alienator88/homebrew-cask/sentinel``` instead of ```brew install alienator88/homebrew-cask/sentinel-app```

Using the link on the website, I was unable to install the app via homebrew...I had to add the -app for it to work!

**Comment by alienator88** [comment]
Nice catch, should be fixed now. (Might take a bit for the site caching to update)
Thank you!
