### ISSUE TITLE
Sequoia 15.0 (24A335)

### ISSUE THREAD

**Issue by petomane1** [alienator88/Sentinel#6]
Hi I've installed Sentinel on my macbook pro with Sequoia 15.0 (24A335) but I cannot revert back gatekeeper (no cursor to enable it on the app) it says "Gatekkeper is disabled" even if I remove the profile.
Thanks
<img width="568" alt="Screenshot 2024-09-11 alle 10 29 32" src="https://github.com/user-attachments/assets/7bf4e0ae-2257-42d2-ad78-981bd42dea97">

**Comment by alienator88** [comment]
So on Sequoia when the profile is removed, the OS doesn't automatically switch gatekeeper back. 
You can turn it back on manually by changing the dropdown in Privacy & Security to anything other than Anywhere.
![Screenshot 2024-09-11 at 11 16 02 AM](https://github.com/user-attachments/assets/9379e76e-7986-4689-a70b-f7ec5f5ab5fd)

I will work on it to see if I can automate that switch when the profile is removed.

**Comment by alienator88** [comment]
Looks like I might need to create an "Enable" and a "Disable" profile for gatekeeper if I want to automate that in Sequoia..

**Comment by alienator88** [comment]
Yeah, that makes sense. I can probably go back to the pre-sequoia toggle switch if I take this route.
Thanks for catching this though, I didn't think about the profile removal not setting gatekeeper back to off automatically.

**Comment by alienator88** [comment]
Release this fix shortly in v1.7

**Comment by petomane1** [comment]
Thanks I’ll wait for it !
Il 11 set 2024, 21:01 +0200, Alin Lupascu ***@***.***>, ha scritto:

**Comment by alienator88** [comment]
Out now

**Comment by petomane1** [comment]
Great !
Il 11 set 2024, 21:13 +0200, Alin Lupascu ***@***.***>, ha scritto:
