### ISSUE TITLE
Sentinel >> Check for Updates menu does nothing?

### ISSUE THREAD

**Issue by perez987** [alienator88/Sentinel#7]
Good afternoon. Latest version 1.7. Checking for updates on startup (according to what we have in Settings) works fine, in console I can see the info:
```
/Applications/Sentinel.app/Contents/MacOS/Sentinel
Updater: next update date is in the future, skipping (10/14/24)
Updater: No announcement for this version
```
But the `Sentinel >> Check for Updates` menu seems to do nothing, no info to the user and no messages in console.
Can you comment on this?
Thank you very much.

**Comment by perez987** [comment]
@alienator88 
Thank you! 
Anyway, this is a very useful app on Sequoia.

**Comment by alienator88** [comment]
Fixed in v1.8.

**Comment by perez987** [comment]
@alienator88 
Thank you!!!

**Comment by alienator88** [comment]
The setting basically prevents the app from showing the update badge or the update pop-up window. In the background on launch, it still pulls the latest version and release notes from the repo. Just doesn't display it to the user at all.

**Comment by alienator88** [comment]
@LesterJitsi side note, I made some changes to the updater now so when setting to Never it won't make any network calls at all. I think you were right to think of that. Change will be out in next release.
