### ISSUE TITLE
Cannot open Zip on Mac

### ISSUE THREAD

**Issue by MC242** [alienator88/Sentinel#8]
Topic says it. I cannot open the Zip on a Mac, no matter what program I try.

**Comment by alienator88** [comment]
I doubt this is a problem with the app, it seems to open fine on my end with multiple computers and VMs. 
That release has been out for 2 weeks at least and there's been no other reports of issues opening the zip file.
Can you try this maybe?
[Sentinel.zip](https://github.com/user-attachments/files/17316732/Sentinel.zip)

**Comment by alienator88** [comment]
I don't see why the computer type would be a problem, it could be OS related.
Can you open Terminal and run: `unzip /Users/USERNAME/Downloads/Sentinel.zip`
Make sure to replace the path with your username or the folder where you have the file downloaded.
It should show an error there if it fails to do it in Terminal as well.

Github won't let me upload .app files it looks like, it has to be a zip.

**Comment by MC242** [comment]
This is really strange. The terminal does not output an error, but the file is not in the folder.
mc@Mac-Pro ~ % unzip /Users/mc/Downloads/Sentinel.zip 
Archive:  /Users/mc/Downloads/Sentinel.zip
   creating: Sentinel.app/
   creating: Sentinel.app/Contents/
   creating: Sentinel.app/Contents/_CodeSignature/
   creating: Sentinel.app/Contents/MacOS/
   creating: Sentinel.app/Contents/Resources/
  inflating: Sentinel.app/Contents/Info.plist  
  inflating: Sentinel.app/Contents/PkgInfo  
  inflating: Sentinel.app/Contents/_CodeSignature/CodeResources  
  inflating: Sentinel.app/Contents/MacOS/Sentinel  
  inflating: Sentinel.app/Contents/Resources/AppIcon.icns  
  inflating: Sentinel.app/Contents/Resources/Assets.car  
mc@Mac-Pro ~ %

**Comment by alienator88** [comment]
Your Terminal directory was `mc@Mac-Pro ~`, the tilde means your Home folder, so `/Users/mc`.
Check that folder for the file.

**Comment by MC242** [comment]
Ah there it is. Thank you! I found it now. :)

**Comment by alienator88** [comment]
Sweet! Glad it worked.
Super weird issue though, I've never seen that before.
You could try the app Unarchiver for the future, that's what I use for unzipping stuff.

**Comment by MC242** [comment]
The app The Unarchiver is even more weird on my site. I had an old version which was not working. Installed the latest version from the App Store, clicked on open and it said could not open. Deleted it from the programs folder, tried to install it again, now I cannot even install it anymore...

**Comment by alienator88** [comment]
It sounds like your OS has all sorts of issues. I would suggest reinstalling the OS clean from scratch, especially if you recently upgraded to Sequoia. Lots of bugs in that one.

**Comment by MC242** [comment]
Thanks, I'm on latest Sonoma 14.7. There are definitely issues, yes. But I rather try to resolve them instead of making a clean install where I then get other issues... 
But anyway, that's my problem I guess...

**Comment by alienator88** [comment]
Yeah, I get that.
Well good luck then!
